### ISSUE TITLE
No src/ directory in master

### ISSUE THREAD

**Issue by DeltaMethod721** [hiclib/pastis#31]
Hi I installed using pip, didn't find src/. I noticed that there's no src/ directory in master branch. Have them been permanently removed? I don't need to specify IPOPT information in makefile?

**Comment by aakashsur** [comment]
It looks like the preferred method is to do sudo pip install pastis rather than using IPOPT.  I think at this point it has been integrated or written out. If you install via pip, you should be able to clone this repo, and test the example under /examples/pastis_example and it should work without further configuration.

**Comment by NelleV** [comment]
That is correct! Thanks @aakashsur  for answering this question.
