### ISSUE TITLE
NA value from the output structure

### ISSUE THREAD

**Issue by chenggonghan** [hiclib/pastis#70]
Hi,

I have two questions about the package:

(1) When I ran the example data contained in the package,  several rows of the structure file contain 'nan' value. Is it normal?

(2) I could not replicate the result someone produced about 2 years ago using PASTIS (Not because of randomness, not even close). Any possible major change might contribute to this?  I noticed that Ipopt was used for the optimization, but now L-BFGS-B is used.  Could this be the reason?  Or do you still have the old code which I can have a try?

Thank you very much!

Chenggong

**Comment by NelleV** [comment]
Hello,

Sorry for the slow reply. It seems i missed this ticket.

The NA corresponds to loci with no associated contact count data (probably due to a filtering step in the normalization procedure or non-mappable region).

I indeed switched from IPOPT to L-BFGS-B but the underlying model is identical, so while the results may be different, they shouldn't be drastically different. The randomness due to initialization can induce large changes due to low contact counts, but should preserve any striking feature (such as centromere localization in yeast or plasmodium data, or domains in larger organisms).
The old code is still available, but it would help to know which version was used (here are all the old versions of pastis: https://github.com/hiclib/pastis/tags)

Thanks,
Nelel

**Comment by chenggonghan** [comment]
Thank you very much, Nelle!
